-- 코드를 입력하세요
-- 2022년 1월 도서 판매 데이터 기준 (SALES_DATE)
-- 저자 별, 카테고리 별 매출액 (TOTAL_SALES = 판매량 * 판매가) 구해
-- 저자 ID(AUTHOR_ID), 저자명(AUTHOR_NAME), 카테고리(CATEGORY), 매출액(SALES) 리스트를 출력
-- 저자 ID를 오름차순, 카테고리를 내림차순

SELECT A.AUTHOR_ID, A.AUTHOR_NAME, BB.CATEGORY, BB.TOTAL_SALES
FROM AUTHOR A JOIN (SELECT B.CATEGORY, B.AUTHOR_ID, SUM(B.PRICE * BS.TOTAL) AS TOTAL_SALES
                    FROM BOOK B LEFT JOIN (SELECT BOOK_ID, SUM(SALES) AS TOTAL
                                      FROM BOOK_SALES
                                      WHERE SALES_DATE BETWEEN '2022-01-01' AND '2022-01-31'
                                      GROUP BY BOOK_ID) BS
                    USING(BOOK_ID)
                    GROUP BY B.AUTHOR_ID, B.CATEGORY) BB
USING(AUTHOR_ID)
ORDER BY A.AUTHOR_ID, BB.CATEGORY DESC;


# SELECT B.CATEGORY, B.AUTHOR_ID, SUM(B.PRICE * BS.TOTAL) AS TOTAL_SALES
# FROM BOOK B JOIN (SELECT BOOK_ID, COUNT(SALES) AS TOTAL
#                 FROM BOOK_SALES
#                 WHERE SALES_DATE BETWEEN '2022-01-01' AND '2022-01-31'
#                 GROUP BY BOOK_ID) BS
# USING(BOOK_ID)
# GROUP BY B.AUTHOR_ID, B.CATEGORY;

# SELECT BOOK_ID, COUNT(SALES) AS TOTAL
# FROM BOOK_SALES
# WHERE SALES_DATE BETWEEN '2022-01-01' AND '2022-01-31'
# GROUP BY BOOK_ID;