-- 코드를 입력하세요
-- CAR_RENTAL_COMPANY_CAR : 대여 중인 자동차
-- CAR_RENTAL_COMPANY_RENTAL_HISTORY : 대여 기록
-- CAR_RENTAL_COMPANY_DISCOUNT_PLAN : 자동차 종류 별 대여 기간 종류 별 할인 정책

-- 자동차 종류가 '세단' 또는 'SUV' 인 자동차 중
-- 2022년 11월 1일부터 2022년 11월 30일까지 대여 가능
-- 30일간의 대여 금액이 50만원 이상 200만원 미만인 자동차
-- 자동차 ID, 자동차 종류, 대여 금액(컬럼명: FEE) 리스트를 출력
-- 대여 금액을 기준으로 내림차순, 자동차 종류를 기준으로 오름차순, 자동차 ID를 기준으로 내림차순

WITH MONTHLY_FEE AS (
    SELECT C.CAR_ID, C.CAR_TYPE, C.DAILY_FEE, C.OPTIONS, P.DISCOUNT_RATE, FLOOR(C.DAILY_FEE*30*(1-DISCOUNT_RATE/100)) AS TOTAL_FEE
    FROM CAR_RENTAL_COMPANY_CAR C JOIN CAR_RENTAL_COMPANY_DISCOUNT_PLAN P
    USING(CAR_TYPE)
    WHERE P.DURATION_TYPE = '30일 이상'
)

SELECT C.CAR_ID, C.CAR_TYPE, F.TOTAL_FEE AS FEE
FROM CAR_RENTAL_COMPANY_CAR C JOIN MONTHLY_FEE F USING(CAR_ID)
WHERE C.CAR_TYPE IN('세단','SUV')
AND C.CAR_ID NOT IN(
                    SELECT CAR_ID
                    FROM CAR_RENTAL_COMPANY_RENTAL_HISTORY
                    WHERE START_DATE <= '2022-11-30' AND END_DATE >= '2022-11-01'
            )
AND F.TOTAL_FEE >= 500000 AND F.TOTAL_FEE < 2000000
ORDER BY 3 DESC, 2, 1 DESC;