-- 코드를 입력하세요
-- 자동차 종류가 '세단' 또는 'SUV' 인 자동차 중
-- 2022년 11월 1일부터 2022년 11월 30일까지 대여 가능하고, 
-- 30일간의 대여 금액이 50만원 이상 200만원 미만인 자동차
-- 자동차 ID, 자동차 종류, 대여 금액(컬럼명: FEE) 리스트를 출력
-- 대여 금액을 기준으로 내림차순, 자동차 종류를 기준으로 오름차순, 자동차 ID를 기준으로 내림차순

# SELECT CH.CAR_ID, CH.CAR_TYPE, CH.DAILY_FEE*30*P.DISCOUNT_RATE*0.01 AS FEE
# FROM (SELECT *
#      FROM CAR_RENTAL_COMPANY_CAR C JOIN (SELECT *
#                                         FROM CAR_RENTAL_COMPANY_RENTAL_HISTORY
#                                         WHERE MONTH(START_DATE) NOT IN (11) AND MONTH(END_DATE) NOT IN (11)) H
#      USING(CAR_ID)
#      WHERE C.CAR_TYPE IN ('세단', 'SUV')) CH JOIN CAR_RENTAL_COMPANY_DISCOUNT_PLAN P
# USING(CAR_TYPE)
# WHERE P.DURATION_TYPE = '30일 이상' AND CH.DAILY_FEE*30*P.DISCOUNT_RATE*0.01 BETWEEN 500000 AND 2000000;


SELECT C.CAR_ID, C.CAR_TYPE, FLOOR(C.DAILY_FEE*30*(1-P.DISCOUNT_RATE*0.01)) AS FEE
FROM CAR_RENTAL_COMPANY_CAR C JOIN CAR_RENTAL_COMPANY_DISCOUNT_PLAN P
USING(CAR_TYPE)
WHERE P.DURATION_TYPE = '30일 이상' AND FLOOR(C.DAILY_FEE*30*(1-P.DISCOUNT_RATE*0.01)) BETWEEN 500000 AND 2000000
AND C.CAR_TYPE IN ('세단', 'SUV')
AND C.CAR_ID NOT IN (SELECT CAR_ID
                 FROM CAR_RENTAL_COMPANY_RENTAL_HISTORY
                 WHERE START_DATE <= '2022-11-30' AND END_DATE >= '2022-11-01')
ORDER BY 3 DESC, 2, 1 DESC;

# SELECT *
# FROM CAR_RENTAL_COMPANY_CAR C JOIN CAR_RENTAL_COMPANY_RENTAL_HISTORY H
# WHERE H.START_DATE <= '2022-11-30' AND H.END_DATE >= '2022-11-01'
# GROUP BY H.CAR_ID;