-- 코드를 입력하세요
-- 음식종류별로 즐겨찾기수가 가장 많은 식당
# SELECT FOOD_TYPE, REST_ID, REST_NAME, MAX(FAVORITES) AS FAVORITES
# FROM REST_INFO
# GROUP BY FOOD_TYPE
# ORDER BY FOOD_TYPE;

SELECT R.FOOD_TYPE, R.REST_ID, R.REST_NAME, R.FAVORITES
FROM REST_INFO R JOIN (SELECT FOOD_TYPE, MAX(FAVORITES) AS FAVORITES
                      FROM REST_INFO
                      GROUP BY FOOD_TYPE) T
ON R.FOOD_TYPE = T.FOOD_TYPE AND R.FAVORITES = T.FAVORITES
ORDER BY FOOD_TYPE DESC;




# 한식	00001	은돼지식당	734
# 일식	00004	스시사카우스	230
# 양식	00003	따띠따띠뜨	102
# 분식	00008	애플우스	151