-- 코드를 작성해주세요
-- 물고기의 종류 별 물고기의 이름, 잡은 수 출력
-- 잡은 수 기준으로 내림차순

# SELECT COUNT(ID) AS FISH_COUNT, FISH_TYPE
# FROM FISH_INFO
# GROUP BY FISH_TYPE;

SELECT COUNT(FISH_NAME) AS FISH_COUNT, FISH_NAME
FROM FISH_NAME_INFO A JOIN FISH_INFO B
USING(FISH_TYPE)
GROUP BY FISH_NAME
ORDER BY 1 DESC;