-- 코드를 입력하세요
-- 생산일자가 2022년 5월인 식품
-- 식품 ID, 식품 이름, 총매출
-- 총매출을 기준으로 내림차순, 식품 ID를 기준으로 오름차순 

SELECT P.PRODUCT_ID, P.PRODUCT_NAME, SUM(P.PRICE*O.AMOUNT) AS TOTAL_SALES
FROM FOOD_PRODUCT P JOIN FOOD_ORDER O
USING(PRODUCT_ID)
WHERE MONTH(O.PRODUCE_DATE) IN (5)
GROUP BY PRODUCT_ID
ORDER BY 3 DESC, 1;