-- 코드를 입력하세요
-- 09:00부터 19:59까지
-- 각 시간대별로 입양이 몇 건이나 발생했는지 조회
-- 시간대 순으로 정렬

SELECT HOUR(DATETIME) AS HOUR, COUNT(DATETIME) AS COUNT
FROM ANIMAL_OUTS
WHERE HOUR(DATETIME) BETWEEN '9' AND '19'
GROUP BY HOUR(DATETIME)
ORDER BY 1;